### ISSUE TITLE
Create 'addToDo' function using TDD

### ISSUE THREAD

**Issue by Jen-Harris** [FAC-11/week2-baja#4]
The should leave the input argument todos unchanged
Returns a new array, it should contain todos with the newTodo added to the end.
Adds an id to the newTodo. You can use the generateId function to create an id.
should consider using: array.concat

**Comment by BartBucknill** [comment]
@Jen-Harris @astroash can we close this issue now? function and tests are written and committed to master.

**Comment by Jen-Harris** [comment]
👍
